### ISSUE TITLE
Bug: Change password confirm value not checked

### ISSUE THREAD

**Issue by dubicube** [securingdata/smartsafe-client-desktop#7]
Steps to produce:
- Goto "change password"
- Write a password in the "New Password Value" field
- Write the same password in the "Confirm value" field
- Write another password in the "New Password Value" field (just deleting a char for example)
- Clic Ok
=> The token effectively has the new password, even if the "Confirm value" field is different from the "New Password Value" field.
(Green icon for the second field also stay green even if the 2 fields are different)

By the way, it would be helpful to know why the icon of the first field is red or yellow (i can guess it is from the password size, but it is not obvious).

**Comment by securingdata** [comment]
Bug fixed in version 1.0.1. Thanks for reporting.

Concerning the status icon (red, yellow, green), two things:
- a tooltip text is displayed when leaving the mouse cursor a few seconds on the concerned textfield.
- the help has been updated and contains the conditions to be fulfilled on such textfields.
